/*
 * Token Requestor ID API
 * An API that allows On-behalf of Token Requestors such as Payment Service Providers to bulk request TRIDs for their merchants.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.wallee.sdk.trid.model;

import com.google.gson.annotations.SerializedName;
import java.util.Objects;
import com.wallee.sdk.trid.model.TokenRequestorsArrayRequest;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * RequestTokenRequestorRequestSchema
 */

public class RequestTokenRequestorRequestSchema {
  @SerializedName("requestId")
  private String requestId = null;

  @SerializedName("tokenRequestors")
  private List<TokenRequestorsArrayRequest> tokenRequestors = new ArrayList<TokenRequestorsArrayRequest>();

  public RequestTokenRequestorRequestSchema requestId(String requestId) {
    this.requestId = requestId;
    return this;
  }

   /**
   * __REQUIRED__&lt;br&gt; Unique identifier for the request. Only alpha-numeric characters [a-zA-Z0-9].
   * @return requestId
  **/
  public String getRequestId() {
    return requestId;
  }

  public void setRequestId(String requestId) {
    this.requestId = requestId;
  }

  public RequestTokenRequestorRequestSchema tokenRequestors(List<TokenRequestorsArrayRequest> tokenRequestors) {
    this.tokenRequestors = tokenRequestors;
    return this;
  }

  public RequestTokenRequestorRequestSchema addTokenRequestorsItem(TokenRequestorsArrayRequest tokenRequestorsItem) {
    this.tokenRequestors.add(tokenRequestorsItem);
    return this;
  }

   /**
   * __REQUIRED__&lt;br&gt; The information on the entities requesting a Token Requestor ID
   * @return tokenRequestors
  **/
  public List<TokenRequestorsArrayRequest> getTokenRequestors() {
    return tokenRequestors;
  }

  public void setTokenRequestors(List<TokenRequestorsArrayRequest> tokenRequestors) {
    this.tokenRequestors = tokenRequestors;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestTokenRequestorRequestSchema requestTokenRequestorRequestSchema = (RequestTokenRequestorRequestSchema) o;
    return Objects.equals(this.requestId, requestTokenRequestorRequestSchema.requestId) &&
        Objects.equals(this.tokenRequestors, requestTokenRequestorRequestSchema.tokenRequestors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestId, tokenRequestors);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestTokenRequestorRequestSchema {\n");
    
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    tokenRequestors: ").append(toIndentedString(tokenRequestors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

